# This configuration and the setup was based from ripgrep by Andrew Gallant (BurntSushi). 
# https://github.com/BurntSushi/ripgrep

language: rust
rust:
  - stable
env:
  RUST_BACKTRACE: full
  PROJECT_NAME: texture-notes
cache: cargo

# For now, it only support the operating systems I always get to use. 
matrix:
  fast_finish: true
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu

    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
      arch: arm64
      addons:
        apt:
          - gcc-arm-linux-gnueabihf

    - os: windows
      env: TARGET=x86_64-pc-windows-gnu

    - os: windows
      env: TARGET=x86_64-pc-windows-msvc

# Installing all of the required dependencies for packaging the program.
install: 
  - chmod +x ci/install.sh
  - ci/install.sh
before_script:
  - gem install asciidoctor
script:
  - make create-docs
  - chmod +x ci/script.sh
  - ci/script.sh

before_deploy: ci/before_deploy.sh
deploy:
  provider: pages
  file_glob: true
  on:
    tags: true
    branch: master
