= Changelog
All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].



== Unreleased 


=== Added 

* Support for template files instead of storing in the configuration file. 
Custom templates are now possible by separating them in a dedicated folder. 
For the sake of performance, it can only have support for top-level files. 
Folder-based templates similar to https://github.com/gohugoio/hugo/[Hugo] archetypes is considered but it is tentative. 

* An `init` command for initializing profiles. 
On a related note, if the resulting path is not valid, any commands will cause an error unless it is initialized first. 

* Support for custom compiling commands. 

* Add an optional metadata for the subjects through `info.toml`. 
It is also used for the templates that makes use of the subject metadata. 

* Add a simple note filter system for the subjects. 
This enables narrowing the notes without interruption with the rest of the filesystem. 

* A `master` subcommand. 
A dedicated subcommand for interacting with the master note system. 

* A user manual for the program. 
It is created with an https://asciidoctor.org/[Asciidoctor] document. 


=== Changed 

* Rewrite the application with the https://www.rust-lang.org/[Rust] language. 

* Restructure the application with its own library crate. 
Making it possible to create other binaries with the same application logic. 

* Change the structure of the commands by assigning unit subcommands. 
It is no longer possible to make multiple types and multiple input (e.g., `--notes SUBJECT_1 NOTE_1 --subject SUBJECT_2 SUBJECT_3`) with a single command. 
This is due to the limitations of https://github.com/clap-rs/clap[`clap`]. 
(I think it's not that large of a compromise anyway.) 

* Revise the binder system. 
From this point, the binder is now referred to as the **shelf** or the **base directory**. 
** Make the shelf system modular for easier maintenance. 
** A shelf is still composed of **subjects** (terminology may change in the future). 
Each subject can have a specific metadata file. 
** Remove the database entirely. 
Now, the binder system is entirely dependent of the filesystem. 

* Revise the profile system. 
** The common files folder has been removed. 
** Now, the profile and the shelf are no longer required to be on the same folder. 

* Update the subject to be more path-like. 
It is normalized similarly to a path. 
It can also can be made into multiple path components instead of representing one subject. 
This allows for more flexibility and intuition in interacting with the program. 

* Templates support from https://docs.python.org/3/library/string.html#custom-string-formatting[Python template strings] to https://github.com/sunng87/handlebars-rust[Handlebars Rust implementation]. 
** The templates are also `.hbs` files in the templates folder. 

* Restructure the profile directory structure for neater custom configurations and easier organization. 
** The default profile location is stored with the respective config folder of the OS. 
This allows Texture Notes to be simpler and modular. 
Although, this sacrifices the multiple user aspect (though that's not needed at this point). 
** The profile metadata filename has been changed to `.profile.toml`. 
** Templates has been moved to its own folder at `.templates/`. 

* Revise the main note system. 
The terminology is also changed as the master note system to be more intuitive. 
** The master note is now named as `_master.tex` instead of `main.tex`. 
** The master note system also relies on the filtered notes of the subject. 
This enables more control on how the master note should be generated. 
** The master note also makes use of the templates. 


=== Removed

* Remove the shelf database. 
** The reason: I simply don't use it anymore. 
It also adds complexity for a simple niche tool (that is also intended for learning Rust). 
Overall, it's a waste of time and resources to dwell on it. 
(Nevermind the problems that goes along with synchronizing and validating the database and the filesystem and all that.)
** Along with the database, remove the global ID system for shelf items (e.g., notes, subjects). 
** As a consequence of the removal, the `open` subcommand is also removed since it is a niche feature and only useful with the database. 

* Remove the common files folder (`styles/`) in the profile. 
(At this point, it's pointless though a cross-platform way of creating symbolic links would be nice.
Maybe a `helpers` subcommand where various helper functions are called would be considered.) 
