= Texture Notes 

A lecture notes manager that aims for self-studying and university classes. 
It is mainly compose of a command line program where you can easily manage your LaTeX notes. 

For now, the notes manager is specifically created for my specific workflow so no there's not much room for general use-cases. 

Also since this is my first project made with https://www.rust-lang.org/[Rust], you'll have to excuse my bad codebase for a little bit. 
Nonetheless, pull requests for improvements are always welcome! 




== Objectives 

While creating this program, I have certain objectives to attain. 
Setting up and openly stating the objectives can make you learn the strengths and limitations of the program. 

* Create a personal knowledge base (made with LaTeX) that is easily searchable and retrievable. 
* Automate LaTeX files management including adding, deleting, and compiling documents. 

Furthermore, this program is specifically created for my workflow which leaves little room for other use cases. 
I hope implementing some features that mitigates against that (but not fully). 




== Usage 

In order to make use of this application, you need to have the following programs installed already in the system: 

* A LaTeX distribution (http://www.tug.org/interest.html#free[here's a list of options, if you haven't installed one])
* https://www.ctan.org/pkg/latexmk/[Latexmk]


=== Quick start 

To prevent getting a mess, Texture Notes needs a profile which is located in a folder named `texture-notes-profile`. 




== Architecture 

Texture Notes v2 uses Rust for building the core and command line interface. 
It also use https://sqlite.org/index.html[SQLite] for the database. 

A Texture Notes profile is composed of the profile input, notes, and styles for customizable options. 
The note manager also enforces a specific folder structure with the data. 

image::./docs/assets/texture-notes-profile.svg[]




== Features 

Here are the features to be implemented whenever possible. 

* Hooks scripts using Rust. 
* Exclude the new note in the database. 

I would also like to improve the program on the following areas: 

* Data design which is quite messy as of v2.0.0. 
There has to be a better way for it without entirely relying with a database. 
* Performance to be improved after the core features has been implemented. 
For now, it's not a priority. 
* Cross-platform compatibility. 
As a user of multiple OS (i.e., Windows and Linux), I really like to make this possible to easily use this program. 
