= texture-notes(1)
Gabriel Arazas
2019-12-31
:toc:
:doctype: manpage
:manmanual: Texture Notes Manual
:mansource: Texture Notes v2.0.0
:man-linkstyle: pass:[red R < >]

:default-template-name: _default
:templates-folder: .templates
:template-file-ext: hbs
:profile-metadata-file: .profile.toml
:subject-metadata-file: info.toml
:master-note-file: _master.tex
:master-default-template: master/_default




== Name 

texture-notes - a note manager for LaTeX documents; inspired from Gilles Castel's LaTeX note management workflow post (https://castel.dev/post/lecture-notes-3/)




== Sypnosis 

*texture-notes* [_GLOBAL OPTIONS_] [_SUBCOMMAND_] [_SUBCOMMAND OPTIONS_] [_SUBCOMMAND ARGUMENT(S)_]




== Global options 

*-p, --profile*=[_PATH_]::
The location of the profile. 
By default, it is located on the default configuration folders of the operating system as defined by the https://crates.io/crates/directories[`directories` crate]. 

*-s, --shelf*=[_PATH_]::
The base directory. 
By default, this is the current working directory. 




== Subcommands 

*init*::
Initialize a profile. 

*add*::
Add a subject or a note. 

*remove*::
Remove a subject or a note. 

*compile*::
Compile a set of notes from a subject. 

*master*:: 
Master note-related interactions. 

*help*::
Print the help section of the subcommand or the application. 




== User guide 


=== Initializing and customizing a profile 

To get started with Texture Notes, one will have to initialize a profile. 
To initialize a profile, just run the `init` subcommand. 

[source, shell]
----
texture-notes init
----

This initializes a profile at the default config folder of the operating system. 
See the <<Default config locations>> appendix section for more details. 

A profile contains the following data:

* A profile metadata which is stored in `{profile-metadata-file}`. 
The TOML file should have the keys `name` and `version` along with the correct data types (i.e., string). 
Custom keys can be added which is useful when creating note templates which will be discussed later in the manual. 

* A set of templates in `{templates-folder}` directory. 
It is a key-value store with the name of the `.tex` files as the key. 


=== Using Texture Notes 

Now a profile is available, you can now create some subjects and notes in a directory referred to as the *base directory* or the *shelf*. 

You can view the available subcommands at the <<Subcommands>> section. 
Most of the subcommands for interacting with the shelf requires an inner subcommand indicating whether it's a subject or a note. 

Here are some of the examples when using Texture Notes. 

[source, shell]
----
texture-notes add subjects "Calculus I" "Calculus II"

texture-notes compile notes "Calculus I" -- "Introduction to limits" "Taylor series"

texture-notes remove subjects "Calculus II"
----

A *subject* in Texture Note is just a folder with a metadata file named `{subject-metadata-file}`. 

For convenience, you can refer to the same subject as long as the resulting kebab-case string is the same. 

For example, consider the following folder structure. 

[source]
----
university
├── year-1
│   ├── semester-1
│   │   ├── calculus-i
│   │   │   ├── introduction-to-limitations.tex
│   │   │   ├── taylor-series.tex
│   │   │   └── info.toml
│   │   ├── computer-design
│   │   └── web-programming
│   └── ...
└── ...
----

You can refer to the Calculus I from the first year folder in different ways assuming the base directory starting from the `university` folder. 

[source, shell]
----
texture-notes add notes "Year 1/Semester 1/Calculus I" -- NOTES...
texture-notes add notes "year-1/semester-1/calculus-i" -- NOTES...
texture-notes add notes "year-1/semester-1/Calculus I" -- NOTES...
----

As long as the resulting kebab-case of each component in the path is the same with the folder, it is considered as the same subject in the filesystem. 
If the `name` key in the metadata file is not present or valid, the name of the subject is referred to by the last path component. 
For certain cases, this can be distinct when creating notes or the subject. 

The same applies for referring to notes. 
As long as the resulting kebab-case is the same, it refers to the same note in the filesystem. 


=== Note templates 

Texture Notes has a simple templating system for your LaTeX documents. 
As briefly mentioned, the templates are located in a profile specifically in the `{templates-folder}` folder. 

Internally, the templates is represented as a key-value store. 
The key-value store comes from the folder that expects a list of `.{template-file-ext}` files with the file name as the key. 

Texture Notes use https://crates.io/crates/handlebars[a Rust implementation of Handlebars] as the templating language. 
It is definitely important to make sure the templates is valid. 

The template store primarily use the `{default-template-name}` template as the default key. 
The `{default-template-name}` template has the following value. 

[source, latex]
----
\documentclass[class=memoir, crop=false, oneside, 14pt]{standalone}

% document metadata
\author{ {{~name~}} }
\title{ {{~note.title~}} }
\date{ {{~date~}} }

\begin{document}
Sample content.

{{subject.name}}
\end{document}
----

To override the default template, just create `{default-template-name}.{template-file-ext}` on the templates folder. 

As previously said, Texture Notes uses a templating engine specifically https://crates.io/crates/handlebars/3.0.0-beta.5[a Rust implementation] of https://handlebarsjs.com/[Handlebars]. 
To set dynamic values, a Handlebars expression delimited by two pairs of curly braces (`{{$EXPR}}`). 
Practically in using Texture Notes, these are often used to refer to a https://github.com/toml-lang/toml[TOML] value. 

When creating a note, a TOML table is forming from different sources such as the profile and subject metadata. 

For example, let's create a note titled "Introduction to limits" under the subject "Calculus I". 
Assuming the shelf is the current directory, the shell command would look like the following. 

[source, shell]
----
texture-notes add notes "Calculus I" -- "Introduction to limits"
----

The following TOML table is then formed in the note creation process. 

[source, toml]
----
name = "STUDENT_NAME"
version = "VERSION"
_date = "2019-01-06"

# The rest of the keys in `profile.toml`. 
# ...

[note]
title = "Introduction to limits"
_file = "introduction-to-limits.tex"
# ...
_relpath_from_shelf = "introduction-to-limits.tex"

[subject]
name = "Calculus I"
_file = "calculus"
# ...
_relpath_from_shelf = ""
# The rest of the keys in `info.toml` of the subject.
----

This is where setting custom keys can be handy. 
If you want a globally applied data, you can add a few fields on the `{profile-metadata-file}` in the profile directory. 
It is then accessible in the template as a top-level field. 

For subject-specific data, you can add a `{subject-metadata-file}` and create a note. 
It is accessible under the `subject` table. 


=== LaTeX documents compilation 

Texture Notes can do basic automation of compiling LaTeX documents in parallel through threads. 

This is mainly used with the `compile` subcommand. 

[source, shell]
----
texture-notes compile notes "Calculus I" -- "Introduction to limits"
----

You can change the number of threads compiling the documents with the `--thread-count` option. 
The default compilation process spawns four threads. 

You can also change the default
The default compilation command is `'latexmk -pdf {{note}}'`. 
You can override the default command by setting the `command` key in the `{profile-metadata-file}`. 
Similar to note templates, the command template uses Handlebars. 
The available fields for substituing is `note` which is the basically the resulting file name (e.g., "Introduction to calculus" to "introduction-to-calculus.tex"). 

You can also compile certain files either by: 

* Setting with the command line option `--files` which accepts similar array of strings. 
The command line option has the highest precedence. 
* Setting a key in `{subject-metadata-file}` named *_files* which is an array of strings (file globs). 
Even if there is a `_files` key, the command line option will override the note filter. 


=== Master notes 

Texture Notes also allows to create *master notes*. 

A master note is a note combined from the filtered notes of a subject. 
It is associated with one and only one subject. 
It is also only dynamically generated and cannot be statically generated. 
Each master note also has a file name of `{master-note-file}`. 

To generate a master note, run the *master* subcommand. 

[source, shell]
----
texture-notes master "Calculus I"
----

By default, the master note template is `{master-default-template}`. 
To override the default, create a file named `{master-default-template}.{template-file-ext}` in the templates folder of the profile. 

This also immediately compiles the master note. 
To skip the compilation step, simply provide the skip compilation flag (`-s`). 




== Metadata keys reference 

A reference of the keys Texture Notes officially recognizes. 

*`{profile-metadata-file}`*:: 

* `name` - The name of the profile. 
This field is required. 
* `version`- The version of the profile. 
This field is required. 
This key may or may not have expanded upon future versions. 
* `command` - The compilation command for the notes. 
If this key is absent in the file, it uses `latexmk -pdf {{note}}`. 

*`{subject-metadata-file}`*::

* `name` - The name of the subject. 
Mainly used for creating the note template. 
* `_files` - An array of globs pointing to a note. 
This is mainly used as a filter for retrieving all notes of the specified subject. 
The default value is `["*.tex"]`. 




== Exit status 

*0*::
Successful termination. 

*1*::
General errors — e.g., invalid or nonexistent profile, TOML or Handlebars parsing error. 




== Repository 

Git repository::
https://github.com/foo-dogsquared/texture-notes-v2

Issue tracker::
https://github.com/foo-dogsquared/texture-notes-v2/issues




[appendix]
== Built-in TOML 

Most component (i.e., subjects, notes) in Texture Notes has a resulting TOML associated with it. 
This is mostly used for creating notes (and master notes). 


=== Profile object (TOML) 

For the profile, the TOML is simply the metadata file. 
The TOML from the profile is often where building the resulting TOML first starts. 


=== Subject object 

For the subject, there are two data sources: a dynamic TOML and the data from the metadata file. 
If the subject has a metadata file (`{subject-metadata-file}`), it will build the TOML from there. 
The following keys are then set with dynamic values and assign under the profile TOML as a table named *subject*. 

CAUTION: Any data from the subject metadata file with the same keys will be overridden with the autogenerated values (except for one case). 
It is generally advised not to use the following keys. 

* `name` - The name of the subject. 
If there is `{subject-metadata-file}` with the field, it will use it instead. 
* `_slug` - The resulting kebab case of the name. 
* `_path` - The path of the subject. 
* `_relpath_to_shelf` - The resulting relative path from the subject directory to the shelf. 
* `_relpath_from_shelf` - The resulting relative path from the shelf to the subject directory. 


=== Note object 

The note also has a resulting TOML with the following keys. 

* `title` - The title of the note. 
* `_slug` - The resulting title in kebab case. 
* `_file` - The resulting file name of the note. 
It is basically the note title in kebab case appended with `.tex`. 
* `_path` - The resulting path of the note. 
* `_relpath_to_shelf` - The resulting relative path from the directory of the note to the shelf. 
* `_relpath_from_shelf` - The resulting relative path from the shelf to the directory of the note. 


=== Master note object 

The master note is mostly similar to a note TOML data. 

* `notes` - The filtered notes. 
It contains the individual note TOML. 
* `subject` - The subject of the master note. 
It contains the subject TOML. 
* `_path` - The path of the master note. 
* `_relpath_to_shelf` - The relative path from the directory of the master note to the shelf. 
* `_relpath_from_shelf` - The inverse of `_relpath_to_shelf`. The relative path from the shelf to the directory of the master note. 


=== During note creation 

The resulting TOML of the different components are different from one process to another. 
In creating a note, the following TOML is formed. 

[source, toml]
----
name = "NAME"
version = "VERSION"
_date = "2020-01-07"

# The rest of the keys in `profile.toml`. 

# The subject TOML
[subject]
# ...

# The note TOML
[note]
# ...
----


=== During master note creation 

The resulting TOML when creating the master note is similar to the resulting TOML from note creation. 

[source, toml]
----
name = "NAME"
version = "VERSION"
_date = "2020-01-07"

# The rest of the keys in `profile.toml`. 

# The subject TOML
[subject]
# ...

# The master note TOML
[_master]
# ...
----




[appendix]
== Default config locations

By default, the profile location uses the config folder of the operating system. 

* For Linux, the config folder is at `$XDG_CONFIG_HOME/texture-notes` or at `$HOME/.config/texture-notes`. 
* For Windows, the configuration is stored at `%APPDATA%/texture-notes`. 
* For MacOS, it is at `$HOME/Library/Preferences/texture-notes`. 

Specifically, Texture Notes utilizes the https://crates.io/crates/directories[`directories` crate from crates.io]. 
You can refer to the crates.io page for more details. 
