= lanoma(1)
Gabriel Arazas
2019-12-31
:toc:
:doctype: manpage
:program: Lanoma
:manmanual: {program} Manual
:mansource: {program} v0.1.0
:man-linkstyle: pass:[red R < >]

:binary-name: lanoma
:default-template-name: _default
:templates-folder: .templates
:template-file-ext: hbs
:profile-metadata-file: .profile.toml
:subject-metadata-file: info.toml
:master-note-file: _master.tex
:master-default-template: master/_default




== Name 

{binary-name} - a glorified basic note manager for LaTeX documents that could've been easily created with shell scripts; inspired from Gilles Castel's LaTeX note management workflow post (https://castel.dev/post/lecture-notes-3/)




== Sypnosis 

*{binary-name}* [_GLOBAL OPTIONS_] [_SUBCOMMAND_]... [_SUBCOMMAND OPTIONS_] [_SUBCOMMAND ARGUMENT(S)_]...




== Global options 

*-p, --profile*=[_PATH_]::
The location of the profile. 
By default, it is located on the default configuration folders of the operating system as defined by the https://crates.io/crates/directories[`directories` crate]. 

*-s, --shelf*=[_PATH_]::
The base directory. 
By default, this is the current working directory. 




== Subcommands 

*init*::
Initialize a profile. 

*add*::
Add a subject or a note. 
footnote:[If you're creating notes, I recommend to use https://github.com/foo-dogsquared/hantemcli[hantemcli] which is another project of mine to easily render Handlebars templates in the command line. It could also create templates with data formats other than TOML.]

*remove*::
Remove a subject or a note. 

*compile*::
Compile a set of notes from a subject. 

*master*:: 
Master note-related interactions. 

*help*::
Print the help section of the subcommand or the application. 




== User guide 


=== Initializing and customizing a profile 

To get started with {program}, one will have to initialize a profile. 
To initialize a profile, just run the `init` subcommand. 

[source, shell]
----
lanoma init
----

This initializes a profile at the default config folder of the operating system. 
See the <<Default config locations>> appendix section for more details. 

A profile contains the following data:

* A profile metadata which is stored in `{profile-metadata-file}`. 
The TOML file should have the keys `name` and `version` along with the correct data types (i.e., string). 
Custom keys can be added which is useful when creating note templates which will be discussed later in the manual. 

* A set of templates in `{templates-folder}` directory. 
It is a key-value store with the name of the `.{template-file-ext}` files as the key. 


=== Using {program} 

Now a profile is available, you can now create some subjects and notes in a directory referred to as the *base directory* or the *shelf*. 

You can view the available subcommands at the <<Subcommands>> section. 
Most of the subcommands for interacting with the shelf requires an inner subcommand indicating whether it's a subject or a note. 

Here are some of the examples when using {program}. 

[source, shell]
----
lanoma add subjects "Calculus I" "Calculus II"

lanoma compile notes "Calculus I" -- "Introduction to limits" "Taylor series"

lanoma remove subjects "Calculus II"
----

A *subject* in {program} is just a folder with a metadata file named `{subject-metadata-file}`. 

For convenience, you can refer to the same subject as long as the resulting kebab-case string is the same. 

For example, consider the following folder structure. 

[source]
----
university
├── year-1
│   ├── semester-1
│   │   ├── calculus-i
│   │   │   ├── introduction-to-limitations.tex
│   │   │   ├── taylor-series.tex
│   │   │   └── info.toml
│   │   ├── computer-design
│   │   └── web-programming
│   └── ...
└── ...
----

You can refer to the Calculus I from the first year folder in different ways assuming the base directory starting from the `university` folder. 

[source, shell]
----
lanoma add notes "Year 1/Semester 1/Calculus I" -- NOTES...
lanoma add notes "year-1/semester-1/calculus-i" -- NOTES...
lanoma add notes "year-1/semester-1/Calculus I" -- NOTES...
----

As long as the resulting kebab-case of each component in the path is the same with the folder, it is considered as the same subject in the filesystem. 
If the `name` key in the metadata file is not present or valid, the name of the subject is referred to by the last path component. 
For certain cases, this can be distinct when creating notes or the subject. 

The same applies for referring to notes. 
As long as the resulting kebab-case is the same, it refers to the same note in the filesystem. 

That said, with this implementation, {program} will not recognize notes (and subjects) in the filesystem that are not in valid kebab-case. 
You can exploit this to make certain notes and subjects hidden simply by adding and renaming the file with an invalid kebab-case character (e.g., an underscore (`_`), an exclamation point (`!`), dot (`.`)). 


=== Note templates 

{program} has a simple templating system for your LaTeX documents. 
As briefly mentioned, the templates are located in a profile specifically in the `{templates-folder}` folder. 

Internally, the templates is represented as a key-value store. 
The key-value store comes from the folder that expects a list of `.{template-file-ext}` files with the file name as the key. 

{program} use https://crates.io/crates/handlebars[a Rust implementation of Handlebars] as the templating language. 
It is definitely important to make sure the templates is valid. 

The template store primarily use the `{default-template-name}` template as the default key. 
The `{default-template-name}` template has the following value. 

[source, latex]
----
\documentclass[class=memoir, crop=false, oneside, 14pt]{standalone}

% document metadata
\author{ {{~profile.name~}} }
\title{ {{~note.title~}} }
\date{ {{~reldate~}} }

\begin{document}
Sample content.

{{subject.name}}
\end{document}
----

To override the default template, just create `{default-template-name}.{template-file-ext}` on the templates folder. 
The Handlebars configuration within the {program} also comes with a few helper functions for convenience. 
Check out the <<Templating>> section in the appendix for more details. 

As previously said, {program} uses a templating engine specifically https://crates.io/crates/handlebars/3.0.0-beta.5[a Rust implementation] of https://handlebarsjs.com/[Handlebars]. 

Practically in templating with Handlebars and {program}, these are often used to refer to a https://github.com/toml-lang/toml[TOML] value. 
When creating a note, a TOML table is forming from different sources such as the profile and subject metadata. 

For example, let's create a note titled "Introduction to limits" under the subject "Calculus I". 
Assuming the shelf is the current directory, the shell command would look like the following. 

[source, shell]
----
lanoma add notes "Calculus I" -- "Introduction to limits"
----

The following TOML table is then formed in the note creation process. 

[source, toml]
----
[profile]
name = "STUDENT_NAME"
version = "VERSION"
# The rest of the keys in `profile.toml`. 
# ...

[shelf]
path = "##FULL PATH TO THE SHELF##"

[note]
title = "Introduction to limits"
file = "introduction-to-limits.tex"
path_in_shelf = "##FULL PATH TO THE FILE##"

[subject]
name = "Calculus I"
_path_in_shelf = "##FULL PATH TO THE SUBJECT FOLDER##"
# The rest of the keys in `info.toml` of the subject if there's any. 
----

This is where setting custom keys can be handy. 
If you want a globally applied data, you can add a few fields on the `{profile-metadata-file}` in the profile directory. 
It is then accessible in the template as a top-level field. 

For subject-specific data, you can add a `{subject-metadata-file}` and create a note. 
It is accessible under the `subject` table. 


=== LaTeX documents compilation 

{program} can do basic automation of compiling LaTeX documents in parallel through threads. 

This is mainly used with the `compile` subcommand. 

[source, shell]
----
lanoma compile notes "Calculus I" -- "Introduction to limits"
----

You can change the number of threads compiling the documents with the `--thread-count` option. 
The default compilation process spawns four threads. 

You can also change the default
The default compilation command is `'latexmk -pdf {{note}}'`. 
You can override the default command by setting the `command` key in the `{profile-metadata-file}`. 
Similar to note templates, the command template uses Handlebars. 
The available fields for substituing is `note` which is the basically the resulting file name (e.g., "Introduction to calculus" to "introduction-to-calculus.tex"). 

You can also compile certain files either by: 

* Setting with the command line option `--files` which accepts similar array of strings. 
The command line option has the highest precedence. 
* Setting a key in `{subject-metadata-file}` named *_files* which is an array of strings (file globs). 
Even if there is a `_files` key, the command line option will override the note filter. 


=== Master notes 

{program} also allows to create *master notes*. 

A master note is a note combined from the filtered notes of a subject. 
It is associated with one and only one subject. 
Each master note also has a file name of `{master-note-file}`. 

To generate a master note, run the *master* subcommand. 

[source, shell]
----
lanoma master "Calculus I"
----

By default, the master note template is `{master-default-template}`. 
For future references, the default master template has the following content. 

[source, latex]
----
\documentclass[class=memoir, crop=false, oneside, 12pt]{standalone}

% document metadata
\author{ {{~profile.name~}} }
\title{ {{~subject.name~}} }
\date{ {{~reldate~}} }

\begin{document}
% Frontmatter of the class note

{{#each master.notes}}
Note: {{this.name}} {{this.path_in_shelf}}
{{/each }}

\end{document}
----

To know more about the TOML object of the master note, please refer to the <<Built-in object data>> section. 

To override the default, create a file named `{master-default-template}.{template-file-ext}` in the templates folder of the profile. 

This also immediately compiles the master note. 
To skip the compilation step, simply provide the skip compilation flag (`-s`/`--skip-compilation`). 




== Exit status 

*0*::
Successful termination. 

*1*::
General errors — e.g., invalid or nonexistent profile, TOML or Handlebars parsing error. 




== Repository 

Git repository::
https://github.com/foo-dogsquared/lanoma

Issue tracker::
https://github.com/foo-dogsquared/lanoma/issues




[appendix]
== Config reference 

A reference of the keys {program} officially recognizes. 

*`{profile-metadata-file}`*:: 

* `name` - The name of the profile. 
This field is required. 
* `version`- The version of the profile. 
This field is required. 
This key may or may not have expanded upon future versions. 
* `command` - A Handlebars string for the compilation command of the notes. 
The command is assumed to be executed on the folder of the subject. 
If this key is absent in the file, it uses `pdflatex {{note}}`. 

*`{subject-metadata-file}`*::

* `name` - The name of the subject. 
Mainly used for creating the note template. 
* `_files` - An array of globs pointing to a note. 
This is mainly used as a filter for retrieving all notes of the specified subject. 
The default value is `["*.tex"]`. 
* `command` - A Handlebars string for the compilation command of the notes. 
The command is assumed to be executed on the folder of the subject. 
If this key is absent in the file, it uses `latexmk -pdf {{note}}`. 




[appendix]
== Built-in object data 

Most component (i.e., subjects, notes) in {program} has a resulting object data associated with it. 
This is mostly used for creating notes (and master notes). 


=== Profile object 

For the profile, the TOML is simply the metadata file. 
The TOML from the profile is often where building the resulting TOML first starts. 


=== Shelf object 

The shelf object simply contains the `path` key where it holds the full path of the shelf. 


=== Subject object 

For the subject, there are two data sources: a dynamic TOML and the data from the metadata file. 
If the subject has a metadata file (`{subject-metadata-file}`), it will build the TOML from there. 
The following keys are then set with dynamic values and assign under the profile TOML as a table named *subject*. 

CAUTION: Any data from the subject metadata file with the same keys will be overridden with the autogenerated values (except for one case). 
It is generally advised not to use the following keys. 

* `name` - The name of the subject. 
If there is `{subject-metadata-file}` with the field, it will use it instead. 
* `_full_name` - The full name of the subject including the previous subject components (i.e., `Year 1/Semester 1/Calculus` as the full name while `Calculus` is the name). 
* `_path` - The path of the subject. 
* `_path_in_shelf` - The path of the subject relative to the shelf. 
(Take note of the prepended underscore.)


=== Note object 

The note also has a resulting TOML with the following keys. 

* `title` - The title of the note. 
* `file` - The resulting file name of the note. 
It is basically the note title in kebab case appended with `.tex`. 
* `path_in_shelf` - The resulting path of the note. 


=== Master note object 

The master note is mostly similar to a note TOML data. 

* `notes` - The filtered notes. 
It contains the individual note TOML. 
* `subject` - The subject of the master note. 
It contains the subject TOML. 
* `path_in_shelf` - The path of the master note. 


=== During note creation 

The resulting TOML of the different components are different from one process to another. 
In creating a note, the following TOML is formed. 

[source, toml]
----
# The profile object
[profile]
# ...

# The shelf object
[shelf]
# ...

# The subject TOML
[subject]
# ...

# The note TOML
[note]
# ...
----


=== During master note creation 

The resulting TOML when creating the master note is similar to the resulting TOML from note creation. 

[source, toml]
----
# The profile object
[profile]
# ...

# The shelf object
[shelf]
# ...

# The subject TOML
[subject]
# ...

# The master note TOML
[master]
# ...
----




[appendix]
== Default config locations

By default, the profile location uses the config folder of the operating system. 

* For Linux, the config folder is at `$XDG_CONFIG_HOME/lanoma` or at `$HOME/.config/lanoma`. 
* For Windows, the configuration is stored at `%APPDATA%/lanoma`. 
* For MacOS, it is at `$HOME/Library/Preferences/lanoma`. 

Specifically, {program} utilizes the https://crates.io/crates/directories[`directories` crate from crates.io]. 
You can refer to the crates.io page for more details. 




[appendix]
== Templating 

{program} uses a specific https://crates.io/crates/handlebars[Rust implementation of Handlebars] as the templating language. 


=== Basic syntax 

This section will tackle the basic syntax of https://handlebarsjs.com/[Handlebars]. 
For a more reliable reference, you can go to the https://handlebarsjs.com/[official website] and the https://crates.io/crates/handlebars[the crates.io page]. 

To evaluate an expression, simply delimit them with two pairs of curly brackets (`{{`, `}}`). 

[source, handlebars]
----
{{ ##OBJECT_REFERENCE## }}
{{ profile.name }}
{{ subject.name }}
----

Functions (or helpers) are also a part of Handlebars. 
They are simply referred to by their name and the arguments separated by whitespaces. 

[source, handlebars]
----
{{FUNCTION arg_1 arg_2 ... }}
{{reldate "%F %T %Z" 4}}
{{kebab-case "The quick brown fox jumps over the lazy dog."}}
----

Block helpers needs a declaring pair similar to HTML container tags. 
They are identified with a prepended `#` in the helper name and needs a closing mustache (`/`) of the same name. 

[source, handlebars]
----
{{#if expr}}
Hello
{{/if}}
----

Comments can be made by delimiting the content in comment blocks (i.e., `{{! ##CONTENT## }}`, `{{!-- ##CONTENT## --}}`). 
It will not show up in the output. 

Handlebars also make use of raw escaping with the 'triple-stash' (`{{{ }}}`). 

The curly brackets are often used in LaTeX documents. 
The following Handlebars code will result in a parsing error. 

[source, handlebars]
----
{{!-- This will cause an error. --}}
\title{{{subject.name}} - {{note.title}}}
----

To get around this, you can utilize https://handlebarsjs.com/guide/expressions.html#whitespace-control[whitespace control]. 

Adding a tilde character (`~`) by the braces will trim the surrounding whitespace of the Handlebars expression on that side. 

[source, handlebars]
----
\title{ {{~ subject.name }} - {{note.title ~}} }
-> \title{Calculus - Introduction to Limits}
----

Handlebars (rather the implementation library that {program} uses) also support reusing of the templates with partials. 
This allows to create a skeleton with modular templates (i.e., head, body). 

To import a template, just prepend the name of the template to be imported with `>`. 

[source, handlebars]
----
\begin{document}
{{>TEMPLATE_NAME object_param=.}}
\end{document}
----


=== Helper functions 

The templating language is only enough to cover the most basic of the common use cases. 
It is not as extensive as https://gohugo.io/templates/[Hugo templates]. 

Along with the https://docs.rs/handlebars/3.0.0-beta.5/handlebars/#built-in-helpers[built-in helpers], {program} extends the helper list for convenience. 
As of 2020-01-13, there is no way for the user to add their own helpers. 
It requires modifying the source code and recompiling {program}. 

Here are the list of the helper functions: 


==== Mathematical functions 

The mathematical functions are just simple arithmetic operations. 

* `add` for addition. 
* `sub` for subtraction. 
* `mul` for multiplication. 
* `div` for division. 

These functions are also divided into types: integers and float. 
The arithmetic helpers accept any number of arguments. 

CAUTION: The functions are strict and does not cast integers into float and vice versa. 

[source, handlebars]
----
{{add-int 1 2 3 4 5}}
{{add-float 1.0 2.0 3.0 4.0 5.0}}

{{sub-int 5 3 2}}
{{sub-float 1.0 2.0 3.0 4.0 5.0}}

{{! Variables are also accepted. }}
{{! Assuming subject.id is '5'. }}
{{add-int subject.id * 10}}

{{! Invalid types are discarded. }}
{{! The expression below will result in '5'. }}
{{add-int subject.id * 10.0}}
----

Any invalid argument (e.g., floating numbers in an integer addition) is discarded and replaced with the https://en.wikipedia.org/wiki/Identity_element[identity element] of the operation. 


==== Case conversion functions 

There are multiple string case conversion helpers for converting a string: 

NOTE: The letter case helpers (besides the uppercase and lowercase function) is implemented using the https://docs.rs/heck/0.3.1/heck/[heck] library. 
It drops the punctuation and does not feature smart casing. 

* `upper-case` - Convert a string into upper case. 
* `lower-case` - Convert a string into lower case. 
* `kebab-case` - Convert a string into kebab case where all words are in lowercase, punctuations and whitespace are stripped, and joined with a hyphen (`-`). 
* `snake-case` - Convert a string into snake case where all words are in lowercase, punctuations and whitespace are removed, and are joined with an underscore (`_`). 
* `camel-case` - Convert a string into camel case where all whitespace is trimmed and the words are capitalized. 
* `title-case` - Convert a string into title case where all words are capitalized. 

Overall, the argument for the function should be the same. 
All of them needs only one string. 

[source, handlebars]
----
{{CASE_FN STRING}}

{{upper-case "The quick brown fox jumps over the lazy dog."}} 
-> "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG."

{{lower-case "The quick brown fox jumps over the lazy dog."}} 
-> "the quick brown fox jumps over the lazy dog."

{{kebab-case "The quick brown fox jumps over the lazy dog."}} 
-> "the-quick-brown-fox-jumps-over-the-lazy-dog"

{{snake-case "The quick brown fox jumps over the lazy dog."}} 
-> "the_quick_brown_fox_jumps_over_the_lazy_dog"

{{camel-case "The quick brown fox jumps over the lazy dog."}} 
-> "TheQuickBrownFoxJumpsOverTheLazyDog"

{{title-case "The quick brown fox jumps over the lazy dog."}} 
-> "The Quick Brown Fox Jumps Over The Lazy Dog"
----


==== reldate

Generates a string with the relative datetime from today. 
It accepts two parameters: the format of the date and the number of days relative to today. 

[source, handlebars]
----
{{reldate STRING_FORMAT NUMBER_OF_DAYS}}
----

For more information in the date syntax, refer to the https://docs.rs/chrono/0.4.10/chrono/format/strftime/index.html[`chrono::format::strftime` module that {program} uses for detecting the datetime]. 

By default, `reldate` formats today's datetime with `%F`. 

[source, handlebars]
----
{{! Assuming this is executed on 2020-01-12 }}

{{reldate}} 
-> 2020-01-12

{{reldate "%F %T" 3}} 
-> 2020-01-12 23:04:58

{{reldate "%Y-%B-%D" -12}} 
-> 2019-December-12/31/19

{{reldate "%T %Y %B" 1024}} 
-> 23:35:14 2022 November
----


==== relpath

Outputs the relative path from the destination path to the base path. 
Similar to https://docs.python.org/3/library/os.path.html#os.path.relpath[Python `os.path.relpath`], this is done only with path computation. 
The filesystem is not accessed in any way. 

[source, handlebars]
----
{{relpath DESTINATION_PATH BASE_PATH}}
----

If an invalid input is detected, it will be replaced with an empty string (`""`). 
If the output is invalid, it will return an empty string. 

[source, handlebars]
----
{{! Assuming this is executed on 2020-01-12 }}

{{relpath "university/year-1/semester-1" "university/year-2/semester-2"}} 
-> ../../year-1/semester-1

{{relpath "." "university/year-1"}} 
-> ../../.

{{relpath "university/year-1" "."}} 
-> university/year-1

{{relpath ".." "university/year-1"}} 
-> ../../..

{{relpath "university/year-1" "university"}} 
-> year-1

{{relpath "../university/year-1" ".."}} 
-> university/year-1

{{relpath "/dev/sda1 /dev/sda6"}} 
-> ../sda1
----
